name: varvamp-qpcr-workflow

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - cd-hit=4.8.1
  - mafft=7.505
  - biopython
  - pandas
  - matplotlib
  - pillow
  - pymupdf
  - pip
  - pip:
      - varvamp==1.3.2